// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models/event/event.proto

package event

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Duration             int64                `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	UserId               int64                `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BeforeDuration       int64                `protobuf:"varint,7,opt,name=before_duration,json=beforeDuration,proto3" json:"before_duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7a2edf541911069, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Event) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Event) GetBeforeDuration() int64 {
	if m != nil {
		return m.BeforeDuration
	}
	return 0
}

func init() {
	proto.RegisterType((*Event)(nil), "event.Event")
}

func init() { proto.RegisterFile("models/event/event.proto", fileDescriptor_c7a2edf541911069) }

var fileDescriptor_c7a2edf541911069 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0xb4, 0x49, 0x75, 0x0a, 0x15, 0x06, 0xc1, 0x25, 0x17, 0x83, 0x17, 0x73, 0xda,
	0x80, 0xbe, 0x82, 0x1e, 0xbc, 0x06, 0xef, 0x25, 0x71, 0xa6, 0x65, 0x21, 0xe9, 0x86, 0xcd, 0xc4,
	0xb7, 0xf5, 0x5d, 0xa4, 0xb3, 0xb6, 0x78, 0x59, 0xf8, 0xff, 0xfd, 0xe6, 0x9b, 0x01, 0x3b, 0x06,
	0xe2, 0x61, 0x6e, 0xf8, 0x9b, 0x4f, 0x92, 0x5e, 0x37, 0xc5, 0x20, 0x01, 0x73, 0x0d, 0xe5, 0xe3,
	0x31, 0x84, 0xe3, 0xc0, 0x8d, 0x96, 0xfd, 0x72, 0x68, 0xc4, 0x8f, 0x3c, 0x4b, 0x37, 0x4e, 0x89,
	0x7b, 0xfa, 0x31, 0x90, 0xbf, 0x9f, 0x51, 0xdc, 0x41, 0xe6, 0xc9, 0x9a, 0xca, 0xd4, 0xab, 0x36,
	0xf3, 0x84, 0xf7, 0x90, 0x8b, 0x97, 0x81, 0x6d, 0x56, 0x99, 0xfa, 0xb6, 0x4d, 0x01, 0x1d, 0xac,
	0xa9, 0x13, 0xb6, 0xab, 0xca, 0xd4, 0xdb, 0x97, 0xd2, 0x25, 0xbf, 0xbb, 0xf8, 0xdd, 0xe7, 0xc5,
	0xdf, 0x2a, 0x87, 0x25, 0xdc, 0xd0, 0x12, 0x3b, 0xf1, 0xe1, 0x64, 0xd7, 0xea, 0xbe, 0x66, 0xac,
	0x60, 0x4b, 0x3c, 0x7f, 0x45, 0x3f, 0xe9, 0x77, 0xae, 0x7b, 0xfe, 0x57, 0xf8, 0x00, 0x9b, 0x65,
	0xe6, 0xb8, 0xf7, 0x64, 0x0b, 0x1d, 0x2e, 0xce, 0xf1, 0x83, 0xf0, 0x19, 0xee, 0x7a, 0x3e, 0x84,
	0xc8, 0xfb, 0xab, 0x7d, 0xa3, 0xc0, 0x2e, 0xd5, 0x6f, 0x7f, 0x6d, 0x5f, 0xe8, 0x65, 0xaf, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x52, 0xce, 0x76, 0xa7, 0x2a, 0x01, 0x00, 0x00,
}
